// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htspmmemelunoshqvjtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0c3BtbWVtZWx1bm9zaHF2anRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjgyOTcsImV4cCI6MjA2MjkwNDI5N30.UPiyKA07SfJXqDCQxRrgx47wPnq07v21QPft-rhgCus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);